site_name: DER Control Modules Site
theme:
  features:
    - navigation.instant
    - navigation.instant.prefetch
  name: material

plugins:
  - caption

markdown_extensions:
  - attr_list

nav:
  - Home: index.md
  - Interoperability Framework: interoperability-framework.md
    - Interoperability Agent: interoperability.md
  - Controls: controls/index.md
    - Real-Time Control Agent: rt-control.md
    - Scheduler: scheduler.md
  - OpenFMB: openfmb.md
  - Test Cases: test-cases.md
#  - User Guide: user_guide.md
